drop table CONSOLE if exists
drop table GAME if exists
create table CONSOLE (id bigint generated by default as identity (start with 1), console_name varchar(255), primary key (id))
create table GAME (id bigint generated by default as identity (start with 1), title varchar(255), console_id bigint, primary key (id))
alter table GAME add constraint FK2143F2C89492F8 foreign key (console_id) references CONSOLE